using System;
using System.Collections.Generic;
using UnityEngine;

namespace OpenFarCry.Importer.Cgf
{
    // Level-scoped cache for textures GENERATED by the importer (e.g. emission masks
    // derived from a diffuse alpha channel). Distinct from TextureRuntimeCache, which
    // holds textures decoded from VFS files. Scopes mirror CgfMaterialRuntimeCache:
    // ReleaseLevelScope drops a refcount, TrimUnused destroys orphans.
    // Thread-unsafe: main thread only.
    public sealed class CgfScopedTextureCache
    {
        sealed class Entry
        {
            public Texture2D Texture;
            public int RefCount;
            public readonly HashSet<string> Scopes = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        }

        readonly Dictionary<string, Entry> _textures =
            new Dictionary<string, Entry>(StringComparer.Ordinal);
        readonly Dictionary<string, HashSet<string>> _keysByScope =
            new Dictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);

        public Texture2D GetOrCreate(string key, string scopeId, Func<Texture2D> factory)
        {
            if (string.IsNullOrEmpty(key))
                return factory != null ? factory() : null;

            if (_textures.TryGetValue(key, out var entry) && entry.Texture != null)
            {
                if (AttachScope(scopeId, key, entry))
                    entry.RefCount++;
                return entry.Texture;
            }

            var tex = factory?.Invoke();
            if (tex == null)
                return null;

            var created = new Entry { Texture = tex, RefCount = 1 };
            _textures[key] = created;
            AttachScope(scopeId, key, created);
            return tex;
        }

        public void ReleaseLevelScope(string scopeId)
        {
            if (string.IsNullOrWhiteSpace(scopeId) || !_keysByScope.TryGetValue(scopeId, out var keys))
                return;

            foreach (string key in keys)
            {
                if (!_textures.TryGetValue(key, out var entry))
                    continue;
                entry.Scopes.Remove(scopeId);
                if (entry.RefCount > 0)
                    entry.RefCount--;
            }

            _keysByScope.Remove(scopeId);
        }

        public int TrimUnused()
        {
            var toRemove = new List<string>();
            foreach (var pair in _textures)
                if (pair.Value == null || pair.Value.RefCount <= 0 || pair.Value.Texture == null)
                    toRemove.Add(pair.Key);

            for (int i = 0; i < toRemove.Count; i++)
                if (_textures.TryGetValue(toRemove[i], out var entry))
                    RemoveEntry(toRemove[i], entry);

            return toRemove.Count;
        }

        public void Clear()
        {
            foreach (var entry in _textures.Values)
                if (entry?.Texture != null)
                    DestroyTexture(entry.Texture);
            _textures.Clear();
            _keysByScope.Clear();
        }

        public int Count => _textures.Count;

        bool AttachScope(string scopeId, string key, Entry entry)
        {
            if (string.IsNullOrWhiteSpace(scopeId) || entry == null)
                return false;
            if (!entry.Scopes.Add(scopeId))
                return false;

            if (!_keysByScope.TryGetValue(scopeId, out var keys))
            {
                keys = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                _keysByScope[scopeId] = keys;
            }
            keys.Add(key);
            return true;
        }

        void RemoveEntry(string key, Entry entry)
        {
            if (entry.Texture != null)
                DestroyTexture(entry.Texture);

            foreach (string scopeId in entry.Scopes)
            {
                if (_keysByScope.TryGetValue(scopeId, out var keys))
                {
                    keys.Remove(key);
                    if (keys.Count == 0)
                        _keysByScope.Remove(scopeId);
                }
            }

            _textures.Remove(key);
        }

        static void DestroyTexture(Texture2D tex)
        {
            if (tex == null)
                return;
            if (Application.isPlaying)
                UnityEngine.Object.Destroy(tex);
            else
                UnityEngine.Object.DestroyImmediate(tex);
        }
    }
}
